version: "3"

services:
  database:
    build: ./db
    container_name: quorum-db
    ports:
      - "5432:5432"
    env_file:
      - ./db/database.env
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
