FROM redis

# Install required packages for Postgres
#RUN apt-get update && \
#    apt-get install -y postgresql postgresql-contrib

# Install required packages for Redis
#RUN apt-get update && \
#    apt-get install -y redis-server



# Expose the default Redis port
EXPOSE 6379

# Start Postgres and Redis services
# CMD service postgresql start && service redis-server start
# CMD service postgresql start
# CMD service redis-server start

# RUN service postgresql start && service redis-server start

